---
abstract: 'e{val,exec} stuff on pictures'
author:
  - 'Magnus Woldrich <m@japh.se>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-epic
no_index:
  directory:
    - t
    - inc
requires:
  Image::Magick: 0
resources:
  bugtracker: https://github.com/trapd00r/epic/issues
  repository: https://github.com/trapd00r/epic
version: 0.014
